### PR TITLE
bug fix: Bash script do not identify users OS correctly.

### PR DESCRIPTION
**Pull request by amirpiri**
I currently using ubuntu 22.04 and I got error on your bash script: Os not support.
I fixed it, so please review and merge my code
thanks

### CODE REVIEW

**Comment by amirpiri** [comment]
I currently using ubuntu 22.04 and I got error on your bash script: Os not support.
I fixed it, so please review and merge my code
thanks

**Comment by MortezaBashsiz** [comment]
Hi
Thanks
But can not merge this MR
If you install all dependencies, it will work
You just need to check if you already installed all dependencies

**Comment by amirpiri** [comment]
`+ export -f fncCheckIPList
+ clientConfigFile=https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/ClientConfig.json
+ subnetIPFile=NULL
++ fncCheckDpnd
++ osVersion=Linux
+++ uname
++ [[ Linux == \L\i\n\u\x ]]
++ osVersion=Linux
++ command -v jq
++ command -v parallel
++ echo 'I require '\''parallel'\'' but it'\''s not installed. Please install it and try again.'
I require 'parallel' but it's not installed. Please install it and try again.
++ exit 1
+ osVersion=
+ vpnOrNot=NO
+ subnetOrIP=SUBNET
+ downloadOrUpload=BOTH
+ threads=4
+ tryCount=1
+ config=ClientConfig.json
+ speed=100
+ subnetIPFile=custom.subnets
+ [[ '' == \M\a\c ]]
+ [[ '' == \L\i\n\u\x ]]
+ eval set -- ''
++ set --
+ [[ '' == \M\a\c ]]
+ [[ '' == \L\i\n\u\x ]]
+ validArguments=0
+ '[' 0 '!=' 0 ']'
+ [[ NO != \Y\E\S ]]
+ [[ NO != \N\O ]]
+ [[ SUBNET != \S\U\B\N\E\T ]]
+ [[ BOTH != \D\O\W\N ]]
+ [[ BOTH != \U\P ]]
+ [[ BOTH != \B\O\T\H ]]
+ [[ custom.subnets != \N\U\L\L ]]
+ [[ -f custom.subnets ]]
++ date +%Y%m%d-%H%M%S
+ now=20230326-004937
+++ dirname -- cfScanner.sh
++ cd -- .
++ pwd
+ scriptDir=/home/amirhpiri/Programs/CFScanner/bash
+ resultDir=/home/amirhpiri/Programs/CFScanner/bash/../result
+ resultFile=/home/amirhpiri/Programs/CFScanner/bash/../result/20230326-004937-result.cf
+ configDir=/home/amirhpiri/Programs/CFScanner/bash/../config
+ filesDir=/home/amirhpiri/Programs/CFScanner/bash/../files
+ uploadFile=/home/amirhpiri/Programs/CFScanner/bash/../files/upload_file
+ configId=NULL
+ configHost=NULL
+ configPort=NULL
+ configPath=NULL
+ configServerName=NULL
+ progressBar=
+ export 'GREEN=\033[0;32m'
+ GREEN='\033[0;32m'
+ export 'BLUE=\033[0;34m'
+ BLUE='\033[0;34m'
+ export 'RED=\033[0;31m'
+ RED='\033[0;31m'
+ export 'ORANGE=\033[0;33m'
+ ORANGE='\033[0;33m'
+ export 'YELLOW=\033[1;33m'
+ YELLOW='\033[1;33m'
+ export 'NC=\033[0m'
+ NC='\033[0m'
+ fncCreateDir /home/amirhpiri/Programs/CFScanner/bash/../result
+ local dirPath
+ dirPath=/home/amirhpiri/Programs/CFScanner/bash/../result
+ '[' '!' -d /home/amirhpiri/Programs/CFScanner/bash/../result ']'
+ fncCreateDir /home/amirhpiri/Programs/CFScanner/bash/../config
+ local dirPath
+ dirPath=/home/amirhpiri/Programs/CFScanner/bash/../config
+ '[' '!' -d /home/amirhpiri/Programs/CFScanner/bash/../config ']'
+ echo ''
+ echo 'updating config.real'
updating config.real
+ [[ ClientConfig.json == \c\o\n\f\i\g\.\r\e\a\l ]]
+ echo ''

+ echo 'using your own config ClientConfig.json'
using your own config ClientConfig.json
+ cat ClientConfig.json
{
	"id": "815a2e4b-f639-56f5-b498-2c149402ee80",
	"host": "scherehtzhel01.shcree.net",
	"port": "443",
	"path": "api01",
	"serverName": "815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net",
	"subnetsList": "https://raw.githubusercontent.com/MortezaBashsiz/CFScanner/main/bash/cf.local.iplist"
}
+ echo ''

+ fileSize=204800
+ [[ BOTH == \D\O\W\N ]]
+ [[ BOTH == \B\O\T\H ]]
+ echo 'You are testing download'
You are testing download
+ [[ BOTH == \U\P ]]
+ [[ BOTH == \B\O\T\H ]]
+ echo 'You are testing upload'
You are testing upload
+ echo 'making upload file by size 204800 Bytes in /home/amirhpiri/Programs/CFScanner/bash/../files/upload_file'
making upload file by size 204800 Bytes in /home/amirhpiri/Programs/CFScanner/bash/../files/upload_file
+ ddSize=200
+ dd if=/dev/random of=/home/amirhpiri/Programs/CFScanner/bash/../files/upload_file bs=1024 count=200
+ fncValidateConfig ClientConfig.json
+ local config
+ config=ClientConfig.json
+ [[ -f ClientConfig.json ]]
+ echo 'reading config ...'
reading config ...
++ jq --raw-output .id ClientConfig.json
+ configId=815a2e4b-f639-56f5-b498-2c149402ee80
++ jq --raw-output .host ClientConfig.json
+ configHost=scherehtzhel01.shcree.net
++ jq --raw-output .port ClientConfig.json
+ configPort=443
++ jq --raw-output .path ClientConfig.json
+ configPath=api01
++ jq --raw-output .serverName ClientConfig.json
+ configServerName=815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net
+ [[ -n 815a2e4b-f639-56f5-b498-2c149402ee80 ]]
+ [[ -n scherehtzhel01.shcree.net ]]
+ [[ -n 443 ]]
+ [[ -n api01 ]]
+ [[ -n 815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net ]]
+ [[ SUBNET == \S\U\B\N\E\T ]]
+ fncMainCFFindSubnet 4 '' /home/amirhpiri/Programs/CFScanner/bash/../result/20230326-004937-result.cf /home/amirhpiri/Programs/CFScanner/bash 815a2e4b-f639-56f5-b498-2c149402ee80 scherehtzhel01.shcree.net 443 api01 815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net 204800 '' custom.subnets 1 BOTH NO
+ local threads progressBar resultFile scriptDir configId configHost configPort configPath configServerName fileSize osVersion parallelVersion subnetsFile cloudFlareASNList breakedSubnets network netmask downloadOrUpload
+ threads=4
+ progressBar=
+ resultFile=/home/amirhpiri/Programs/CFScanner/bash/../result/20230326-004937-result.cf
+ scriptDir=/home/amirhpiri/Programs/CFScanner/bash
+ configId=815a2e4b-f639-56f5-b498-2c149402ee80
+ configHost=scherehtzhel01.shcree.net
+ configPort=443
+ configPath=api01
+ configServerName=815a2e4b-f639-56f5-b498-2c149402ee80.shcree.net
+ fileSize=204800
+ osVersion=
+ subnetsFile=custom.subnets
+ tryCount=1
+ downloadOrUpload=BOTH
+ vpnOrNot=NO
+ [[ '' == \L\i\n\u\x ]]
+ [[ '' == \M\a\c ]]
+ echo 'OS not supported only Linux or Mac'
OS not supported only Linux or Mac
+ exit 1
`

As you see it's not working. See the debug above

**Comment by MortezaBashsiz** [comment]
`I require 'parallel' but it's not installed. Please install it and try again.`

**Pull request closed without merging**
