### PR TITLE
add upload speed to the fncCheckSpeed function

### PR DESCRIPTION
**Pull request by amini8**
add upload speed to the fncCheckSpeed function

### CODE REVIEW

**Comment by MortezaBashsiz** [comment]
Hi
For real upload test we have to send requests with POST or PUT and this needs to configure on server side to and this way you mentioned to add a file to curl is not functional I think
Unfortunately can not accept this PR

**Comment by amini8** [comment]
yes, we have to option use curl (and you must provide server)

```bash
ulspeed=$(echo -n "scale=2; " && curl --connect-timeout 8 -F "file=@$fileName" http://$1/webtests/ul.php -w "%{speed_upload}" -s -o /dev/null | sed "s/\,/\./g" && echo "/1048576");
echo "$ulspeed" | bc -q | sed "s/$/ MB\/sec/;s/^/\tUpload speed\: /";
```
or use IPERFv3 

```bash
iperf3 -c speedtest.serverius.net -p 5002 -P 10 -4
```

**Comment by MortezaBashsiz** [comment]
iperf is not also solution
because we want to test real v2ray tool

**Comment by amini8** [comment]
if provide server for upload, tell me for fix code

**Pull request closed without merging**
