### PR TITLE
dependency links added

### PR DESCRIPTION
**Pull request by Alirezaaraby**

### CODE REVIEW

**Comment by MortezaBashsiz** [comment]
Thanks for your contribution
Sorry
Can not accept this merge request
Permanent links are not good point for installing packages
each distro and OS will be different

**Comment by Alirezaaraby** [comment]
> Thanks for your contribution Sorry Can not accept this merge request Permanent links are not good point for installing packages each distro and OS will be different

it's true but those links were the official projects link which shows the different ways to install each cli tool.
please check out each link.

**Comment by Alirezaaraby** [comment]
and if those were useful let me know to reopen a pull request.

**Comment by MortezaBashsiz** [comment]
Please resolve the conflicts and create another merge to branch dev

**Pull request closed without merging**
