### PR TITLE
Poetry

### PR DESCRIPTION
**Pull request by Alirezaaraby**

### CODE REVIEW

**Comment by Alirezaaraby** [comment]
@MortezaBashsiz I set a default setting for toml file in the python version but please change it in the way that you want. And do not forget to update `.github/workflows/publish_pypi.yml` and add your pypi token.
You can update the action trigger and you should set the pypi token.

**Comment by MortezaBashsiz** [comment]
Hi
We are not planning to publish in pypi

**Comment by Alirezaaraby** [comment]
What do you think about having a private mirror for its `wheel` file?
If yes i should change something in ci

**Comment by Alirezaaraby** [comment]
> Hi
> 
> Thank you for the contribution but I believe it needlessly complicates the execution for the users. I'm still not convinced why it would be beneficial to do what you suggested

thanks for your response. It's evident that running a python source ( installing the dependencies and ...) is more complicated than installing a build file.

**Comment by tempookian** [comment]
thank you for the clarification and contribution. At this stage, we are not planning to provide a build file.

**Pull request closed without merging**
